### ISSUE TITLE
Does it require any env vars?

### ISSUE THREAD

**Issue by animemandir** [adgsenpai/ADGSTUDIOS-MangaWebsite#1]
How to run this on local? 
I want to test it on local and improve UI, does it requires any secret keys, vars?

**Comment by adgsenpai** [comment]
Hi! You need to make sure Python is installed!

1. Clone the repo
2. pip3 install -r requirements.txt
3. python3 app.py

That should get you going.

This is powered by the Flask engine.

https://flask.palletsprojects.com/en/2.2.x/

Best regards
Mr AD Govindasamy
